const REGISTER_USER = 'REGISTER_USER';
const SUBMITTING = 'SUBMITTING';
const SET_USER = 'SET_USER';
const SET_LOGGEDIN = 'SET_LOGGEDIN';
export {
  REGISTER_USER, SUBMITTING, SET_USER, SET_LOGGEDIN,
};
