const GET_USERS = 'GET_USERS';
const ERROR = 'ERROR';
const SET_IDNP = 'SET_IDNP';
const SET_PHONE = 'SET_PHONE';
const SET_ACCESS_DATE = 'SET_ACCESS_DATE';
const CLEAR_FIELDS = 'CLEAR_FIELDS';
const SET_NAME = 'SET_NAME';
const CLEAR_NAME = 'CLEAR_NAME';
export {
  GET_USERS, ERROR, SET_IDNP, SET_PHONE, SET_ACCESS_DATE, CLEAR_FIELDS, SET_NAME, CLEAR_NAME,
};
